from django.conf.urls import url
from . import views


urlpatterns = [
    #url(r'^$',views.chart_view, name='chart_view'),
    #url(r'^$',views.index, name='index'),
    #url(r'^gchart/$',views.google_chart ,name='google_chart'),
    #url(r'^path/$',views.path_of_purchase ,name='path_of_purchase'),
    url(r'^compare/$',views.comparison_chart ,name='comparison_chart'),
    url(r'^$',views.coffee_flavor_chart ,name='category_intelligence'),
    url(r'^api/get_categories/', views.get_categories, name='get_categories'),
    url(r'^api/get_products/', views.get_products, name='get_products'),
    url(r'^api/get_companies/', views.get_companies, name='get_companies'),
    url(r'^api/get_brands/', views.get_brands, name='get_brands'),
    url(r'^api/get_cities/', views.get_cities, name='get_cities'),
    #url(r'^test/', views.test_run, name='test_run'),
    #url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^api/get_category_volume_json/', views.get_category_volume_json, name='get_category_volume_json'),
    url(r'^api/get_category_value_json/', views.get_category_value_json, name='get_category_value_json'),
    url(r'^api/get_category_test_json/', views.get_category_test_json, name='get_category_test_json'),
    url(r'^api/get_category_company_brand_json/', views.get_category_company_brand_json, name='get_category_company_brand_json'),
    url(r'^api/get_category_brand_json/', views.get_category_brand_json, name='get_category_brand_json'),
    #url(r'^rrg/volume/$',views.rrg_volume),
    #url(r'^rrg/value/$',views.rrg_value),
    url(r'^api/get_contents_last_bag/', views.get_contents_last_shopping_bag, name='get_contents_last_shopping_bag'),
    url(r'^api/get_quantity_last_bag/', views.get_quantity_last_shopping_bag, name='get_quantity_last_shopping_bag'),
    url(r'^api/get_top_five_merchants/', views.get_top_five_merchants, name='get_top_five_merchants'),
    url(r'^api/get_last_month_merchants/', views.get_last_month_merchants, name='get_last_month_merchants'),
    url(r'^api/get_yesterday_products/', views.get_yesterday_products, name='get_yesterday_products'),
    url(r'^api/get_top_five_selling_products/', views.get_top_five_selling_products, name='get_top_five_selling_products'),
    url(r'^api/get_percentage_change_last_month/', views.get_percentage_change_last_month, name='get_percentage_change_last_month'),
    url(r'^api/get_change_last_month/', views.get_change_last_month, name='get_change_last_month'),
    url(r'^api/get_path_map/', views.get_path_map, name='get_path_map'),
    url(r'^path_map/', views.path_map_chart, name='path_map_chart'),
    url(r'^api/get_segment_csv/', views.get_segment_csv, name='get_segment_csv'),
    url(r'^api/get_campaign_csv/', views.get_campaign_csv, name='get_campaign_csv'),
    url(r'^segment/', views.segment_index, name='segment'),
    url(r'^api/get_related_products/', views.get_related_products, name='get_related_products'),
    url(r'^api/get_aaramon_related_products/', views.get_aaramon_related_products, name='get_aaramon_related_products'),
    url(r'^initiate_communication/', views.initiate_communication, name='initiate_communication'),
    url(r'^api/url_decode/', views.url_decode, name='url_decode'),
    url(r'^product_path/', views.product_path, name='product_path'),
    url(r'^api/send_email/', views.send_email, name='send_email'),
    url(r'^api/brand_team_weekly_mail/', views.brand_team_weekly_mail, name='brand_team_weekly_mail'),
    url(r'^unsubscribe/', views.unsubscribe, name='unsubscribe'),
]
